name: DummyApp
 
on:

  pull_request:

    branches: [main]

  push:

    branches: [main]
 
jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout

        uses: actions/checkout@v4.1.7
 
      - name: Set up Node.js

        uses: actions/setup-node@v3

        with:

          node-version: '18'  # Use the Node.js version your project requires
 
      - name: Install Dependencies

        run: npm install  # or 'yarn install' if you use Yarn
 
      - name: Setup Java JDK

        uses: actions/setup-java@v4.2.2

        with:

          distribution: 'temurin'

          java-version: '17'
 
      - name: Build with Gradle

        run: ./gradlew build

        working-directory: android
 
      - name: Upload a Build Artifact

        uses: actions/upload-artifact@v3.2.0-node20

        with:

          name: DummyApp.apk

          path: app/build/outputs/apk/debug/app-debug.apk
 
